---
name: Symbol-Util
version: 0.01
author:
  - 'Piotr Roszatycki <dexter@debian.org>'
abstract: Additional utils for Perl symbols manipulation
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Symbol-Util
  license: http://dev.perl.org/licenses/
  repository: http://dexter-cpan.googlecode.com/svn/Symbol-Util
requires:
  perl: 5.006
provides:
  Symbol::Util:
    file: lib/Symbol/Util.pm
    version: 0.01
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
