---
abstract: 'Additional utils for Perl symbols manipulation'
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Symbol-Util
provides:
  Symbol::Util:
    file: lib/Symbol/Util.pm
    version: 0.0203
requires:
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Symbol-Util
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dex4er/perl-Symbol-Util
version: 0.0203
